# Generated by Django 2.0.6 on 2019-02-07 20:00

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0003_auto_20181016_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC5Imports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('success', models.BooleanField(default=False)),
                ('import_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='batdata',
            name='x_120_Necropsy_perform_x',
            field=models.TextField(verbose_name='Necropsy or specimen voucher performed?'),
        ),
        migrations.RenameField(
            model_name='batdata',
            old_name='x_120_Necropsy_perform_x',
            new_name='x_120_Necropsy_or_spec_x'
        )
    ]
