# Generated by Django 2.0.6 on 2019-02-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0004_auto_20190207_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EC5Imports',
            new_name='EpiCollectImport',
        ),
    ]
