# Generated by Django 3.0.7 on 2020-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0008_auto_20200629_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batdata',
            name='x_74_Family_Rhinonycte_x',
            field=models.TextField(verbose_name='Family: Rhinonycteridae'),
        ),
    ]
