# Generated by Django 3.0.7 on 2020-09-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0012_auto_20200831_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Georgia_barcoding',
            new_name='Barcoding',
        ),
        migrations.RenameModel(
            old_name='Georgia_screening',
            new_name='Screening',
        ),
    ]
