# Generated by Django 3.0.7 on 2021-01-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0015_auto_20201106_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='rerun_sample',
            field=models.TextField(null=True, verbose_name='Was sample RE-RUN?'),
        ),
    ]
