# Generated by Django 3.0.7 on 2021-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0017_screening_rerun_sample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='rerun_sample_type',
            field=models.TextField(null=True, verbose_name='RE-RUN Sample type'),
        ),
    ]
