# Generated by Django 3.0.7 on 2021-01-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0018_screening_rerun_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='rerun_sample_storage_media',
            field=models.TextField(null=True, verbose_name='RE-RUN Sample storage media'),
        ),
    ]
