# Generated by Django 3.0.7 on 2021-01-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0019_screening_rerun_sample_storage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='animal_id',
            field=models.TextField(verbose_name='ANIMAL ID'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='animal_id_reentry',
            field=models.TextField(verbose_name='ANIMAL ID (re-entry)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='sample_id',
            field=models.TextField(verbose_name='SAMPLE ID'),
        ),
    ]
