# Generated by Django 3.0.7 on 2021-01-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0020_auto_20210112_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='confirmation_test_results',
            field=models.TextField(verbose_name='Sequencing result'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='confirmation_test_results_other',
            field=models.TextField(verbose_name='Sequencing result - if "Other"'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='date_confirmation_test',
            field=models.DateTimeField(null=True, verbose_name='Date of sequencing'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='date_rtpcr_1',
            field=models.DateTimeField(null=True, verbose_name='Date of RT-PCR'),
        ),
    ]
