# Generated by Django 3.0.7 on 2021-01-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0022_auto_20210113_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='confirmation_test_notes',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='date_rtpcr_2',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='performed_rtpcr_1',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='performed_rtpcr_2',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='positive_control_1_visible',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='positive_control_2',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='positive_control_2_visible',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='sample_condition',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='storage_facility',
        ),
    ]
