# Generated by Django 3.0.7 on 2021-01-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0023_auto_20210113_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcoding',
            name='sequencing_notes',
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_aligned_cov_seuqence_submitted_to_blast',
            field=models.TextField(null=True, verbose_name='Aligned host sequence (.fasta file) submitted to BLAST'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_date_gel_electrophoresis',
            field=models.DateTimeField(null=True, verbose_name='Date of gel electrophoresis'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_date_rtpcr',
            field=models.DateTimeField(null=True, verbose_name='Date of RT-PCR'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_date_sequenced',
            field=models.DateTimeField(null=True, verbose_name='Date of sequencing'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_gel_electrophoresis_results',
            field=models.TextField(null=True, verbose_name='Gel electrophoresis result'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_gel_photo_labeled',
            field=models.TextField(null=True, verbose_name='Gel photo - labeled'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_host_identified_blast',
            field=models.TextField(null=True, verbose_name='Host species identified using BLAST'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_percent_identity_top_BLAST_match',
            field=models.FloatField(null=True, verbose_name='Percent identity (%) for top BLAST match'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_query_cover_top_BLAST_match',
            field=models.FloatField(null=True, verbose_name='Query cover (%) for top BLAST match'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_raw_host_sequence_ab1',
            field=models.TextField(null=True, verbose_name='Raw host sequence - .ab1 files'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_raw_host_sequence_pdf',
            field=models.TextField(null=True, verbose_name='Raw host sequence - .pdf files'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_raw_host_sequence_txt',
            field=models.TextField(null=True, verbose_name='Raw host sequence - .txt files'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_sample',
            field=models.TextField(null=True, verbose_name='Was sample RE-RUN'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_screenshot_top_5_BLAST_matches',
            field=models.TextField(null=True, verbose_name='Screenshot photo of top 5 BLAST matches'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_sequencing_results',
            field=models.TextField(null=True, verbose_name='Sequencing result'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_sequencing_results_other',
            field=models.TextField(null=True, verbose_name='Sequencing result - if "Other"'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='animal_id',
            field=models.TextField(verbose_name='ANIMAL ID'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='gel_electrophoresis_results',
            field=models.TextField(verbose_name='Gel electrophoresis result'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='sequencing_results',
            field=models.TextField(verbose_name='Sequencing result'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='sequencing_results_other',
            field=models.TextField(verbose_name='Sequencing result - if "Other"'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gel_electrophoresis_notes_comments',
            field=models.TextField(verbose_name='Gel electrophoresis notes'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gel_electrophoresis_results',
            field=models.TextField(verbose_name='Gel electrophoresis result'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='rerun_gel_electrophoresis_results',
            field=models.TextField(null=True, verbose_name='RE-RUN Gel electrophoresis result'),
        ),
    ]
