# Generated by Django 3.0.7 on 2021-01-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0024_auto_20210115_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_aligned_cov_seuqence_submitted_to_blast',
            field=models.TextField(null=True, verbose_name='RE-RUN Aligned host sequence (.fasta file) submitted to BLAST'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_date_gel_electrophoresis',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN Date of gel electrophoresis'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_date_rtpcr',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN Date of RT-PCR'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_date_sequenced',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN Date of sequencing'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_gel_electrophoresis_results',
            field=models.TextField(null=True, verbose_name='RE-RUN Gel electrophoresis result'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_gel_photo_labeled',
            field=models.TextField(null=True, verbose_name='RE-RUN Gel photo - labeled'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_host_identified_blast',
            field=models.TextField(null=True, verbose_name='RE-RUN Host species identified using BLAST'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_percent_identity_top_BLAST_match',
            field=models.FloatField(null=True, verbose_name='RE-RUN Percent identity (%) for top BLAST match'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_query_cover_top_BLAST_match',
            field=models.FloatField(null=True, verbose_name='RE-RUN Query cover (%) for top BLAST match'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_raw_host_sequence_ab1',
            field=models.TextField(null=True, verbose_name='RE-RUN Raw host sequence - .ab1 files'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_raw_host_sequence_pdf',
            field=models.TextField(null=True, verbose_name='RE-RUN Raw host sequence - .pdf files'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_raw_host_sequence_txt',
            field=models.TextField(null=True, verbose_name='RE-RUN Raw host sequence - .txt files'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_screenshot_top_5_BLAST_matches',
            field=models.TextField(null=True, verbose_name='RE-RUN Screenshot photo of top 5 BLAST matches'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_sequencing_results',
            field=models.TextField(null=True, verbose_name='RE-RUN Sequencing result'),
        ),
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_sequencing_results_other',
            field=models.TextField(null=True, verbose_name='RE-RUN Sequencing result - if "Other"'),
        ),
    ]
