# Generated by Django 3.0.7 on 2021-01-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0025_auto_20210118_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcoding',
            name='rerun_sample',
            field=models.TextField(null=True, verbose_name='Was sample RE-RUN?'),
        ),
    ]
