# Generated by Django 3.1.7 on 2021-03-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0026_auto_20210125_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='country',
            field=models.TextField(default='not set', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='screening',
            name='country',
            field=models.TextField(default='not set', verbose_name='Country'),
        ),
    ]
