# Generated by Django 3.1.7 on 2021-10-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0027_auto_20210318_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='positive_control_1',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='rerun_positive_control_1',
        ),
        migrations.AddField(
            model_name='screening',
            name='positive_control',
            field=models.TextField(null=True, verbose_name='Positive control'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_RNA_extraction_method',
            field=models.TextField(null=True, verbose_name='RE-RUN2 RNA extraction method'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_aligned_cov_sequence_submitted_to_blast',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Aligned CoV sequence (.fasta file) submitted to BLAST'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_confirmation_test_results',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Sequencing result'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_confirmation_test_results_other',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Sequencing result - if "Other"'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_coronavirus_identified_blast',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Coronavirus identified by BLAST'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_date_RNA_extraction',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN2 Date of RNA extraction'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_date_confirmation_test',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN2 Date of sequencing'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_date_gel_electrophoresis',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN2 Date of gel electrophoresis'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_date_rtpcr_1',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN2 Date of RT-PCR'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_gel_electrophoresis_results',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Gel electrophoresis result'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_gel_photo_labeled',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Gel photo - labeled'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_negative_control',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Negative control'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_percent_identity_top_BLAST_match',
            field=models.FloatField(null=True, verbose_name='RE-RUN2 Percent identity (%) for top BLAST match'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_positive_control',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Positive control'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_query_cover_top_BLAST_match',
            field=models.FloatField(null=True, verbose_name='RE-RUN2 Query cover (%) for top BLAST match'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_raw_cov_sequence_ab1',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Raw CoV sequence - .ab1 files'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_raw_cov_sequence_pdf',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Raw CoV sequence - .pdf files'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_raw_cov_sequence_txt',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Raw CoV sequence - .txt files'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_sample',
            field=models.TextField(null=True, verbose_name='Was sample RE-RUN2?'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_sample_id',
            field=models.TextField(null=True, verbose_name='RE-RUN2 SAMPLE ID'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_sample_storage_media',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Sample storage media'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_sample_type',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Sample type'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun2_screenshot_top_5_BLAST_matches',
            field=models.TextField(null=True, verbose_name='RE-RUN2 Screenshot photo of top 5 BLAST matches'),
        ),
        migrations.AddField(
            model_name='screening',
            name='rerun_positive_control',
            field=models.TextField(null=True, verbose_name='RE-RUN Positive control'),
        ),
    ]
