# Generated by Django 3.1.7 on 2021-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0031_auto_20211129_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcoding',
            name='rerun2_sample',
            field=models.TextField(null=True, verbose_name='Was sample RE-RUN again ?'),
        ),
    ]
