# Generated by Django 3.1.7 on 2022-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0033_auto_20211129_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='sample_id',
            field=models.TextField(null=True, verbose_name='SAMPLE ID'),
        ),
    ]
