# Generated by Django 3.1.7 on 2022-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0034_barcoding_sample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='sample_type',
            field=models.TextField(null=True, verbose_name='Sample type'),
        ),
    ]
