# Generated by Django 3.1.7 on 2022-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0035_barcoding_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='date_RNA_extraction',
            field=models.DateTimeField(null=True, verbose_name='Date of RNA extraction'),
        ),
    ]
