# Generated by Django 3.1.7 on 2022-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0037_barcoding_rerun_sample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='rerun_sample_type',
            field=models.TextField(null=True, verbose_name='RE-RUN Sample type'),
        ),
    ]
