# Generated by Django 3.1.7 on 2022-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0038_barcoding_rerun_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='rerun2_date_RNA_extraction',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN 2 Date of RNA extraction'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun2_sample_id',
            field=models.TextField(null=True, verbose_name='RE-RUN 2 SAMPLE ID'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun2_sample_type',
            field=models.TextField(null=True, verbose_name='RE-RUN 2 Sample type'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_date_RNA_extraction',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN Date of RNA extraction'),
        ),
    ]
