# Generated by Django 3.1.7 on 2022-03-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0043_auto_20220323_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batdata',
            name='x_113_Estimate_microli_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimate microliters of blood drawn'),
        ),
        migrations.AlterField(
            model_name='trappingevent',
            name='x_46_Number_of_26_mete_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of 2.6 meter nets'),
        ),
        migrations.AlterField(
            model_name='trappingevent',
            name='x_47_Number_of_4_meter_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of 4 meter nets'),
        ),
        migrations.AlterField(
            model_name='trappingevent',
            name='x_48_Number_of_6_meter_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of 6 meter nets'),
        ),
        migrations.AlterField(
            model_name='trappingevent',
            name='x_49_Number_of_9_meter_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of 9 meter nets'),
        ),
        migrations.AlterField(
            model_name='trappingevent',
            name='x_50_Number_of_12_mete_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of 12 meter nets'),
        ),
        migrations.AlterField(
            model_name='trappingevent',
            name='x_51_Number_of_18_mete_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of 18 meter nets'),
        ),
        migrations.AlterField(
            model_name='trappingevent',
            name='x_52_Number_of_harp_tr_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of harp traps'),
        ),
    ]
