# Generated by Django 3.1.7 on 2022-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0046_auto_20220324_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_aligned_cov_seuqence_submitted_to_blast',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Aligned host sequence (.fasta file) submitted to BLAST'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_date_RNA_extraction',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN 3 Date of RNA extraction'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_date_gel_electrophoresis',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN 3 Date of gel electrophoresis'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_date_rtpcr',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN 3 Date of RT-PCR'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_date_sequenced',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN 3 Date of sequencing'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_gel_electrophoresis_results',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Gel electrophoresis result'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_gel_photo_labeled',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Gel photo - labeled'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_host_identified_blast',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Host species identified using BLAST'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_percent_identity_top_BLAST_match',
            field=models.FloatField(null=True, verbose_name='RE-RUN 3 Percent identity (%) for top BLAST match'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_query_cover_top_BLAST_match',
            field=models.FloatField(null=True, verbose_name='RE-RUN 3 Query cover (%) for top BLAST match'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_raw_host_sequence_ab1',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Raw host sequence - .ab1 files'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_raw_host_sequence_pdf',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Raw host sequence - .pdf files'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_raw_host_sequence_txt',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Raw host sequence - .txt files'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_sample',
            field=models.TextField(null=True, verbose_name='Was sample RE-RUN a 3rd time?'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_sample_id',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 SAMPLE ID'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_sample_type',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Sample type'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_screenshot_top_5_BLAST_matches',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Screenshot photo of top 5 BLAST matches'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_sequencing_results',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Sequencing result'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_sequencing_results_other',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Sequencing result - if "Other"'),
        ),
    ]
