# Generated by Django 3.1.7 on 2022-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0047_auto_20220829_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='primer_set',
            field=models.TextField(null=True, verbose_name='Primer set used'),
        ),
    ]
