# Generated by Django 3.1.7 on 2022-09-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0049_auto_20220912_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='rerun3_date_rtpcr_1',
            field=models.DateTimeField(null=True, verbose_name='RE-RUN 3 Date of RT-PCR'),
        ),
    ]
