# Generated by Django 3.1.7 on 2022-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0051_auto_20220912_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcoding',
            name='rerun2_primer_set',
            field=models.TextField(null=True, verbose_name='RE-RUN 2 Primer set used'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun3_primer_set',
            field=models.TextField(null=True, verbose_name='RE-RUN 3 Primer set used'),
        ),
        migrations.AddField(
            model_name='barcoding',
            name='rerun_primer_set',
            field=models.TextField(null=True, verbose_name='RE-RUN Primer set used'),
        ),
    ]
