# Generated by Django 3.1.7 on 2022-09-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wabnet', '0052_auto_20220913_1342'),
        ('wabnet', '0047_auto_20220714_1850'),
    ]

    operations = [
    ]
